[package]
name = "bevy_reload_mods"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { git = "https://github.com/Mathspy/bevy.git", branch = "app-reload", features = ["dynamic_linking"] }
nom = "8.0.0"
